/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRS.UserInterface;

import CRS.AppLogic.Student;
import CRS.AppLogic.studentModel;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;

/**
 *
 * @author aashgar
 */
public class studentsView2 extends javax.swing.JPanel
            implements Observer{

    /**
     * Creates new form studentsView1
     */
    public studentsView2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListStudents = new javax.swing.JList<>();

        jListStudents.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListStudents);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jListStudents;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        DefaultListModel<String> aDefaultListModel=
                new DefaultListModel<String>();
        aDefaultListModel.addElement("Name -- Major -- Grade");
        aDefaultListModel.addElement("====================");
        List<Student> students = ((studentModel) o).getStudents();
        //Sort students based on grade
        Collections.sort(students, new Comparator<Student>(){
            @Override
            public int compare(Student s1, Student s2) {
                return (int) (s2.getGrade() - s1.getGrade());//Sort in ASC
            }
            
        });
        for(Student aStudent: students){
            String row = aStudent.getName();
            row += " -- " + aStudent.getMajor();
            row += " -- " + aStudent.getGrade();
            aDefaultListModel.addElement(row);
        }
        jListStudents.setModel(aDefaultListModel);
    }
}
